// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVaNE6qSsRDTBPIbf3pr2mvmeUeuS81PA',
    appId: '1:856989199753:web:487b0f992b6be6dd524558',
    messagingSenderId: '856989199753',
    projectId: 'stretching-app-c3c33',
    authDomain: 'stretching-app-c3c33.firebaseapp.com',
    storageBucket: 'stretching-app-c3c33.appspot.com',
    measurementId: 'G-DP4DDNGVJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFjDowQwlDmtHAqlez2_nj7S8Otpl1wUo',
    appId: '1:856989199753:android:033a197401091add524558',
    messagingSenderId: '856989199753',
    projectId: 'stretching-app-c3c33',
    storageBucket: 'stretching-app-c3c33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTD5vJgtjgy-dKfeiAxiVUnCca7Xn9asQ',
    appId: '1:856989199753:ios:a4b21c8e95417b3a524558',
    messagingSenderId: '856989199753',
    projectId: 'stretching-app-c3c33',
    storageBucket: 'stretching-app-c3c33.appspot.com',
    iosClientId: '856989199753-25v517uc9f8h5fpvqnq2a5vl5o0aert6.apps.googleusercontent.com',
    iosBundleId: 'com.example.stretchingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTD5vJgtjgy-dKfeiAxiVUnCca7Xn9asQ',
    appId: '1:856989199753:ios:a4b21c8e95417b3a524558',
    messagingSenderId: '856989199753',
    projectId: 'stretching-app-c3c33',
    storageBucket: 'stretching-app-c3c33.appspot.com',
    iosClientId: '856989199753-25v517uc9f8h5fpvqnq2a5vl5o0aert6.apps.googleusercontent.com',
    iosBundleId: 'com.example.stretchingApp',
  );
}
